### ISSUE TITLE
eWallet_MobileApp_Credit card transaction wrongly being displayed as FPX transaction on the Transaction history screen # 58

### ISSUE THREAD

**Issue by ArjunLokanath** [TNGSB/eWallet#59]
When the User performs, a transaction using a Credit card however the Android mobile App displays as FPX in the transaction history details which is incorrect

**Comment by ArjunLokanath** [comment]
As per May from APAC Venture this issue has been fixed but cannot be retested now as FPX is live in Dev environment

**Comment by BavaniS** [comment]
to download live and check

**Comment by ArjunLokanath** [comment]
Need to retest this in the Live environment today

**Comment by markshermanp** [comment]
<Farah 2.12.16> Android-unable to view transaction history. System displayed "invalid end date"

UserID : Annemhd1710

IOS-Able to see the same user transaction history, however debit card transaction still displayed as FPX. Therefore, reopen the defect.

**Comment by markshermanp** [comment]
@mayyeap May, please fix this issue. Thanks

**Comment by mayyeap** [comment]
Hi mark, This case is solved and you may test in 28 dec build. Thanks.

**Comment by farahmohamad** [comment]
To close this defect as tested, the FPX shall displayed as "Online Banking" instead of FPX.

Refer attachment for POT.
![img_3461](https://cloud.githubusercontent.com/assets/23113211/22093018/1aab653a-de3d-11e6-910b-19f0694a0650.PNG)
![image](https://cloud.githubusercontent.com/assets/23113211/22093033/323a1c3c-de3d-11e6-98b0-6aad0c0d35b3.png)

**Comment by farahmohamad** [comment]
Tested with android build 21 and IOS build 14
